"""Policy change event model — records significant policy lifecycle transitions."""

from __future__ import annotations

from datetime import datetime, timezone
from enum import StrEnum
from typing import Any

from pydantic import BaseModel, Field


class PolicyChangeEventType(StrEnum):
    """Types of policy change events."""

    BUNDLE_CREATED = "policy.bundle.created"
    GATE_COMPLETED = "policy.gate.completed"
    PROMOTION_EXECUTED = "policy.promotion.executed"
    ACTIVATION_CREATED = "policy.activation.created"
    ACTIVATION_ROLLED_BACK = "policy.activation.rolled_back"
    ENVIRONMENT_DISABLED = "policy.environment.disabled"
    ENVIRONMENT_ENABLED = "policy.environment.enabled"
    RING_ASSIGNED = "policy.ring.assigned"
    RING_PROMOTED = "policy.ring.promoted"
    RING_DISABLED = "policy.ring.disabled"
    RING_ENABLED = "policy.ring.enabled"
    MANUAL_RELOAD_REQUESTED = "policy.reload.requested"
    ROLLOUT_CREATED = "policy.rollout.created"
    ROLLOUT_STARTED = "policy.rollout.started"
    ROLLOUT_STEP_SUCCEEDED = "policy.rollout.step_succeeded"
    ROLLOUT_COMPLETED = "policy.rollout.completed"
    ROLLOUT_FAILED = "policy.rollout.failed"
    ROLLOUT_CANCELLED = "policy.rollout.cancelled"
    ROLLOUT_APPROVAL_REQUESTED = "policy.rollout.approval.requested"
    ROLLOUT_APPROVAL_APPROVED = "policy.rollout.approval.approved"
    ROLLOUT_APPROVAL_REJECTED = "policy.rollout.approval.rejected"
    ROLLOUT_APPROVAL_EXPIRED = "policy.rollout.approval.expired"
    ROLLOUT_APPROVAL_DECISION_RECORDED = "policy.rollout.approval.decision_recorded"
    ROLLOUT_APPROVAL_QUORUM_REACHED = "policy.rollout.approval.quorum_reached"
    ROLLOUT_APPROVAL_POLICY_DENIED = "policy.rollout.approval.policy_denied"
    RUNTIME_POLICY_EVALUATED = "policy.runtime.evaluated"
    RUNTIME_POLICY_RULE_CREATED = "policy.runtime.rule.created"
    RUNTIME_POLICY_RULE_ENABLED = "policy.runtime.rule.enabled"
    RUNTIME_POLICY_RULE_DISABLED = "policy.runtime.rule.disabled"
    OBSERVABILITY_REPORT_GENERATED = "policy.observability.report_generated"
    OBSERVABILITY_EXPORT_GENERATED = "policy.observability.export_generated"
    OBSERVABILITY_EXPORT_FAILED = "policy.observability.export_failed"
    SIMULATION_VALIDATION_RUN = "policy.simulation.validation_run"
    SIMULATION_REPLAY_RUN = "policy.simulation.replay_run"
    SIMULATION_EXPORT_GENERATED = "policy.simulation.export_generated"
    SIMULATION_PERMISSION_DENIED = "policy.simulation.permission_denied"
    SIMULATION_GATE_RUN = "policy.simulation.gate_run"
    SIMULATION_GATE_PASSED = "policy.simulation.gate_passed"
    SIMULATION_GATE_FAILED = "policy.simulation.gate_failed"
    SIMULATION_GATE_PERMISSION_DENIED = "policy.simulation.gate_permission_denied"
    PROMOTION_GATE_REQUIRED = "policy.promotion.gate.required"
    PROMOTION_GATE_RUN = "policy.promotion.gate.run"
    PROMOTION_GATE_ATTACHED = "policy.promotion.gate.attached"
    PROMOTION_GATE_SATISFIED = "policy.promotion.gate.satisfied"
    PROMOTION_GATE_FAILED = "policy.promotion.gate.failed"
    PROMOTION_GATE_EXPIRED = "policy.promotion.gate.expired"
    PROMOTION_GATE_EXECUTION_BLOCKED = "policy.promotion.gate.execution_blocked"
    PROMOTION_GATE_PERMISSION_DENIED = "policy.promotion.gate.permission_denied"
    ROLLOUT_GATE_RUN = "policy.rollout.gate.run"
    ROLLOUT_GATE_SATISFIED = "policy.rollout.gate.satisfied"
    ROLLOUT_GATE_BLOCKED = "policy.rollout.gate.blocked"
    ROLLOUT_GATE_FAILED = "policy.rollout.gate.failed"
    ROLLOUT_GATE_SKIPPED = "policy.rollout.gate.skipped"
    ROLLOUT_GATE_ATTACHED = "policy.rollout.gate.attached"
    ROLLOUT_GATE_PERMISSION_DENIED = "policy.rollout.gate.permission_denied"
    NOTIFICATION_CREATED = "policy.notification.created"
    NOTIFICATION_SENT = "policy.notification.sent"
    NOTIFICATION_FAILED = "policy.notification.failed"
    NOTIFICATION_RULE_ENABLED = "policy.notification.rule.enabled"
    NOTIFICATION_RULE_DISABLED = "policy.notification.rule.disabled"
    EXPIRATION_SWEEP_STARTED = "policy.expiration.sweep_started"
    EXPIRATION_SWEEP_COMPLETED = "policy.expiration.sweep_completed"
    EXPIRATION_SWEEP_FAILED = "policy.expiration.sweep_failed"
    EXPIRATION_TARGET_EXPIRED = "policy.expiration.target_expired"
    EXPIRATION_PERMISSION_DENIED = "policy.expiration.permission_denied"
    ROLLOUT_HISTORY_RECORDED = "policy.rollout.history.recorded"
    ROLLOUT_HISTORY_VIEWED = "policy.rollout.history.viewed"
    ROLLOUT_TIMELINE_GENERATED = "policy.rollout.timeline.generated"
    ROLLOUT_ANALYTICS_GENERATED = "policy.rollout.analytics.generated"
    ROLLOUT_ANALYTICS_EXPORT_GENERATED = "policy.rollout.analytics.export_generated"
    ROLLOUT_ANALYTICS_EXPORT_FAILED = "policy.rollout.analytics.export_failed"
    ROLLOUT_ANALYTICS_PERMISSION_DENIED = "policy.rollout.analytics.permission_denied"
    FEDERATION_TARGET_CREATED = "policy.federation.target.created"
    FEDERATION_TARGET_ENABLED = "policy.federation.target.enabled"
    FEDERATION_TARGET_DISABLED = "policy.federation.target.disabled"
    FEDERATION_PLAN_CREATED = "policy.federation.plan.created"
    FEDERATION_PLAN_STARTED = "policy.federation.plan.started"
    FEDERATION_PLAN_COMPLETED = "policy.federation.plan.completed"
    FEDERATION_PLAN_FAILED = "policy.federation.plan.failed"
    FEDERATION_PLAN_CANCELLED = "policy.federation.plan.cancelled"
    FEDERATION_CONFLICT_DETECTED = "policy.federation.conflict.detected"
    FEDERATION_HISTORY_RECORDED = "policy.federation.history.recorded"
    FEDERATION_HISTORY_VIEWED = "policy.federation.history.viewed"
    FEDERATION_TIMELINE_GENERATED = "policy.federation.timeline.generated"
    FEDERATION_ANALYTICS_GENERATED = "policy.federation.analytics.generated"
    FEDERATION_ANALYTICS_EXPORT_GENERATED = "policy.federation.analytics.export_generated"
    FEDERATION_ANALYTICS_EXPORT_FAILED = "policy.federation.analytics.export_failed"
    FEDERATION_ANALYTICS_PERMISSION_DENIED = "policy.federation.analytics.permission_denied"
    FEDERATION_APPROVAL_CREATED = "policy.federation.approval.created"
    FEDERATION_APPROVAL_APPROVED = "policy.federation.approval.approved"
    FEDERATION_APPROVAL_REJECTED = "policy.federation.approval.rejected"
    FEDERATION_APPROVAL_ESCALATED = "policy.federation.approval.escalated"
    FEDERATION_APPROVAL_CANCELLED = "policy.federation.approval.cancelled"
    FEDERATION_APPROVAL_PERMISSION_DENIED = "policy.federation.approval.permission_denied"
    FEDERATION_NOTIFICATION_CREATED = "policy.federation.notification.created"
    FEDERATION_NOTIFICATION_SENT = "policy.federation.notification.sent"
    FEDERATION_NOTIFICATION_FAILED = "policy.federation.notification.failed"
    FEDERATION_APPROVAL_ESCALATION_WORKER_TICKED = "policy.federation.approval.escalation_worker_ticked"
    FEDERATION_APPROVAL_ESCALATION_DUE = "policy.federation.approval.escalation_due"
    FEDERATION_APPROVAL_ESCALATION_LOCK_SKIPPED = "policy.federation.approval.escalation_lock_skipped"
    FEDERATION_NOTIFICATION_DLQ_CREATED = "policy.federation.notification.dlq_created"
    FEDERATION_NOTIFICATION_DLQ_RETRIED = "policy.federation.notification.dlq_retried"
    FEDERATION_NOTIFICATION_DLQ_PURGED = "policy.federation.notification.dlq_purged"
    FEDERATION_WORKER_STARTED = "policy.federation.worker.started"
    FEDERATION_WORKER_STOPPED = "policy.federation.worker.stopped"
    FEDERATION_WORKER_TICK_FAILED = "policy.federation.worker.tick_failed"
    FEDERATION_NOTIFICATION_TEMPLATE_CREATED = "policy.federation.notification.template_created"
    FEDERATION_NOTIFICATION_TEMPLATE_UPDATED = "policy.federation.notification.template_updated"
    FEDERATION_NOTIFICATION_TEMPLATE_DISABLED = "policy.federation.notification.template_disabled"
    FEDERATION_NOTIFICATION_PREFERENCE_SET = "policy.federation.notification.preference_set"
    FEDERATION_NOTIFICATION_PREFERENCE_DELETED = "policy.federation.notification.preference_deleted"
    FEDERATION_NOTIFICATION_SUPPRESSED = "policy.federation.notification.suppressed"
    FEDERATION_NOTIFICATION_TEMPLATE_FAILED = "policy.federation.notification.template_failed"
    FEDERATION_WEBHOOK_REPLAY_REQUESTED = "policy.federation.webhook.replay_requested"
    FEDERATION_WEBHOOK_REPLAY_SUCCEEDED = "policy.federation.webhook.replay_succeeded"
    FEDERATION_WEBHOOK_REPLAY_FAILED = "policy.federation.webhook.replay_failed"
    FEDERATION_WEBHOOK_SIGNATURE_VERIFIED = "policy.federation.webhook.signature_verified"
    FEDERATION_WEBHOOK_SIGNATURE_FAILED = "policy.federation.webhook.signature_failed"
    FEDERATION_NOTIFICATION_DELIVERY_EVENT_RECORDED = "policy.federation.notification.observability.event_recorded"
    FEDERATION_NOTIFICATION_SLA_VIOLATION_DETECTED = "policy.federation.notification.sla.violation_detected"
    FEDERATION_NOTIFICATION_ALERT_CREATED = "policy.federation.notification.alert.created"
    FEDERATION_NOTIFICATION_ALERT_ACKNOWLEDGED = "policy.federation.notification.alert.acknowledged"
    FEDERATION_NOTIFICATION_ALERT_RESOLVED = "policy.federation.notification.alert.resolved"
    FEDERATION_NOTIFICATION_REPORT_EXPORTED = "policy.federation.notification.report.exported"
    FEDERATION_NOTIFICATION_ALERT_DELIVERY_TARGET_CREATED = "policy.federation.notification.alert_delivery.target_created"
    FEDERATION_NOTIFICATION_ALERT_DELIVERY_TARGET_UPDATED = "policy.federation.notification.alert_delivery.target_updated"
    FEDERATION_NOTIFICATION_ALERT_DELIVERY_TARGET_DISABLED = "policy.federation.notification.alert_delivery.target_disabled"
    FEDERATION_NOTIFICATION_ALERT_DELIVERY_ATTEMPT_RECORDED = "policy.federation.notification.alert_delivery.attempt_recorded"
    FEDERATION_NOTIFICATION_ALERT_DELIVERY_DLQ_CREATED = "policy.federation.notification.alert_delivery.dlq_created"
    FEDERATION_NOTIFICATION_PROMETHEUS_EXPORTED = "policy.federation.notification.prometheus.exported"
    FEDERATION_NOTIFICATION_JSONL_EXPORTED = "policy.federation.notification.jsonl.exported"
    FEDERATION_NOTIFICATION_RETENTION_CLEANUP_RAN = "policy.federation.notification.retention.cleanup_ran"
    FEDERATION_NOTIFICATION_ROLLUP_BUILT = "policy.federation.notification.rollup.built"


class PolicyChangeEvent(BaseModel):
    """Records a significant policy lifecycle transition."""

    event_id: str = Field(..., description="Unique event identifier (pce_ prefix)")
    event_type: PolicyChangeEventType = Field(..., description="Type of policy change event")
    environment: str | None = Field(default=None, description="Affected environment")
    ring_name: str | None = Field(default=None, description="Affected ring name")
    bundle_id: str | None = Field(default=None, description="Related policy bundle ID")
    activation_id: str | None = Field(default=None, description="Related activation ID")
    assignment_id: str | None = Field(default=None, description="Related ring assignment ID")
    actor_id: str | None = Field(default=None, description="ID of the actor who triggered the event")
    reason: str | None = Field(default=None, description="Human-readable reason for the change")
    data: dict[str, Any] = Field(default_factory=dict, description="Additional event data")
    created_at: datetime = Field(..., description="Timezone-aware creation timestamp")
